spring:
  r2dbc:
    password: root
    username: root
    url: r2dbc:mysql://localhost:3306/for-r2dbc
    name: for-r2dbc

  main:
    allow-circular-references: true
logging:
  level:
    org.springframework.r2dbc: debug